timesheet_date:
  month: month (1-12)
  year: year (current or as int ex. 2017)
  national_holidays: days_list ex. 1,11 or None

timesheets:
  Project_name_1:
    po_number: xxx
    man_days_costs:
      Senior: x
      Medium: x
      Juniro: x
    teams:
      Team_name_1:
        employee_jira_id_1:
          level: internal_company_level (Senior / Medium / Junior)
          holidays/sick_leaves: days_list ex. 1-3,11,15,18-25 or None
          trainings/other_projects: days_list ex. 1-3,11,15,18-25 or None
      Team_name_2:
        eemployee_jira_id_2:
          level: internal_company_level (Senior / Medium / Junior)
          holidays/sick_leaves: days_list ex. 1-3,11,15,18-25 or None
          trainings/other_projects: days_list ex. 1-3,11,15,18-25 or None
  Project_name_2:
    po_number: xxx
    man_days_costs:
      Senior: x
      Medium: x
      Juniro: x
    teams:
      Team_name_1:
        employee_jira_id_1:
          level: internal_company_level (Senior / Medium / Junior)
          holidays/sick_leaves: days_list ex. 1-3,11,15,18-25 or None
          trainings/other_projects: days_list ex. 1-3,11,15,18-25 or None
      Team_name_2:
        eemployee_jira_id_2:
          level: internal_company_level (Senior / Medium / Junior)
          holidays/sick_leaves: days_list ex. 1-3,11,15,18-25 or None
          trainings/other_projects: days_list ex. 1-3,11,15,18-25 or None